plugins:
  - babel
  - jest
  - react
env:
  node: true
  jest: true
parser: babel-eslint
extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - 'plugin:react/recommended'
rules:
  no-console: 0
  linebreak-style: 0